#sudo rm -R /etc/resolv.conf
echo "nameserver 178.22.122.101" > /etc/resolv.conf
echo "nameserver 185.51.200.1" >> /etc/resolv.conf
# Generated by NetworkManager
# nameserver 178.22.122.101
# nameserver 185.51.200.1

# nameserver 10.104.88.8
# nameserver 10.104.88.9
